apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aap-storage
  annotations:
    components.gke.io/component-name: filestorecsi
    components.gke.io/component-version: 0.13.31
    components.gke.io/layer: addon
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  tier: standard
  network: aap-gke
provisioner: filestore.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
